### ISSUE TITLE
Add tests from upstream

### ISSUE THREAD

**Issue by Klaim** [Klaim/fmt-build2#1]
The current test just checks that the project is usable.

Add tests from the upstream repository.

They rely on gmock so maybe https://github.com/build2-packaging/gtest needs to be completed before adding them here.

**Comment by Klaim** [comment]
#6 is required to proceed.

**Comment by kamrann** [comment]
So even though (I presume) the `build2` packages for `gtest` and `gmock` are now good to use, it appears that for whatever reason `fmt` [bundles its own cut down version of them](https://github.com/fmtlib/fmt/tree/master/test/gtest) inside its own `test/` folder. I wonder, should we just follow upstream, or is it safe to ignore that and consume those dependencies via the `build2` packages? The latter seems nicer, but I guess there is something to be said for following upstream too for compatibility reasons.

**Comment by Klaim** [comment]
We usually just go with the packaged version of embedded dependencies, except if there is a good reason. If their reason is only [to avoid pre-compiled binaries](https://github.com/fmtlib/fmt/blob/master/test/gtest/CMakeLists.txt#L4-L7) I dont think there will be a problem, except if include paths are set manually to that directory.

**Comment by kamrann** [comment]
I've updated the PR with commits that have some initial upstream tests setup.
A few of the default configurations fail in some obscure looking ways. Some fail to build the tests, some build them but tests fail. It seems an older version of MSVC can't even build the library.
[CI results](https://ci.cppget.org/@73087f5c-694c-4f52-9325-d791d7c7e2d9?builds) (most failed ones are at the end of pg 3). 

What's usual approach here, just disable the configurations in the CI? Nothing jumps out at me as being likely due to anything in the package configuration rather than just some incompatibility between upstream and particular compiler/stdlib versions. Obviously disabling stuff because it errors is not ideal but at the same time it seems like it would be a never-ending job to try to track down such issues over all those configurations.

**Comment by Klaim** [comment]
The usual strategy depends a lot on the kind of error indeed. What I see in the results
- some compilation failures but with msvc that isnt that old, so I'm a bit surprised; for these you might want to check first if these versions are supposed to be supported by that fmt version, and if they are then maybe get some help from the main author;
- some tests failing like this one:
```
/tmp/dist/fmt-tests-11.0.1-a.0.20240831085835.b5ecdbfcad8b/basics/test/xchar-test.cc:576: Failure
Value of: saturdays
Expected: contains at least one element that is equal to L"s\xE1" L"b."
  Actual: { L"s\xE1" L"b", L"s\xE1." }
  ```
 If I'm reading this correctly, the check should have passed?
 Anyway it's fishy, but it might also be a platform where fmt is not tested regularly.
 
 So what I was doing usually: I asked the author of the lib where I'm stumped, see if it's something known or that makes sense to him.
Note that meanwhile the package can be published: it works on most configs (except that warning coming from build2 about conditional dependency) so it should be usable already.
You could deactivate the platforms that dont work with a message clarifying why, although I'm not sure what would be best to say at the moment as I dont understand the issues either.

**Comment by kamrann** [comment]
Ok most of these issues have been fixed by upstream, but since those fixes are not yet in an upstream release I've disabled the problematic configurations on the CI.

Current status is that the main set of upstream tests are now incorporated.
